all: false
dir: mocks/
filename: '{{.InterfaceName | snakecase}}_mock.go'
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
template: testify
packages:
  packages:
  github.com/Khaym03/kumo/internal/ports:
    config:
      all: true
      dir: internal/mock/ports