// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/Khaym03/kumo/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectorRegistry creates a new instance of MockCollectorRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectorRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectorRegistry {
	mock := &MockCollectorRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectorRegistry is an autogenerated mock type for the CollectorRegistry type
type MockCollectorRegistry struct {
	mock.Mock
}

type MockCollectorRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectorRegistry) EXPECT() *MockCollectorRegistry_Expecter {
	return &MockCollectorRegistry_Expecter{mock: &_m.Mock}
}

// Collectors provides a mock function for the type MockCollectorRegistry
func (_mock *MockCollectorRegistry) Collectors() []ports.Collector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Collectors")
	}

	var r0 []ports.Collector
	if returnFunc, ok := ret.Get(0).(func() []ports.Collector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.Collector)
		}
	}
	return r0
}

// MockCollectorRegistry_Collectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collectors'
type MockCollectorRegistry_Collectors_Call struct {
	*mock.Call
}

// Collectors is a helper method to define mock.On call
func (_e *MockCollectorRegistry_Expecter) Collectors() *MockCollectorRegistry_Collectors_Call {
	return &MockCollectorRegistry_Collectors_Call{Call: _e.mock.On("Collectors")}
}

func (_c *MockCollectorRegistry_Collectors_Call) Run(run func()) *MockCollectorRegistry_Collectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectorRegistry_Collectors_Call) Return(collectors []ports.Collector) *MockCollectorRegistry_Collectors_Call {
	_c.Call.Return(collectors)
	return _c
}

func (_c *MockCollectorRegistry_Collectors_Call) RunAndReturn(run func() []ports.Collector) *MockCollectorRegistry_Collectors_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCollector provides a mock function for the type MockCollectorRegistry
func (_mock *MockCollectorRegistry) RegisterCollector(collector ports.Collector) {
	_mock.Called(collector)
	return
}

// MockCollectorRegistry_RegisterCollector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCollector'
type MockCollectorRegistry_RegisterCollector_Call struct {
	*mock.Call
}

// RegisterCollector is a helper method to define mock.On call
//   - collector ports.Collector
func (_e *MockCollectorRegistry_Expecter) RegisterCollector(collector interface{}) *MockCollectorRegistry_RegisterCollector_Call {
	return &MockCollectorRegistry_RegisterCollector_Call{Call: _e.mock.On("RegisterCollector", collector)}
}

func (_c *MockCollectorRegistry_RegisterCollector_Call) Run(run func(collector ports.Collector)) *MockCollectorRegistry_RegisterCollector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.Collector
		if args[0] != nil {
			arg0 = args[0].(ports.Collector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollectorRegistry_RegisterCollector_Call) Return() *MockCollectorRegistry_RegisterCollector_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCollectorRegistry_RegisterCollector_Call) RunAndReturn(run func(collector ports.Collector)) *MockCollectorRegistry_RegisterCollector_Call {
	_c.Run(run)
	return _c
}
