// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/Khaym03/kumo/internal/pkg/types"
)

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher struct {
	mock.Mock
}

type MockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatcher) EXPECT() *MockDispatcher_Expecter {
	return &MockDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: reqs
func (_m *MockDispatcher) Dispatch(reqs ...*types.Request) {
	_va := make([]interface{}, len(reqs))
	for _i := range reqs {
		_va[_i] = reqs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - reqs ...*types.Request
func (_e *MockDispatcher_Expecter) Dispatch(reqs ...interface{}) *MockDispatcher_Dispatch_Call {
	return &MockDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch",
		append([]interface{}{}, reqs...)...)}
}

func (_c *MockDispatcher_Dispatch_Call) Run(run func(reqs ...*types.Request)) *MockDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*types.Request, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(*types.Request)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) Return() *MockDispatcher_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) RunAndReturn(run func(...*types.Request)) *MockDispatcher_Dispatch_Call {
	_c.Run(run)
	return _c
}

// Finish provides a mock function with given fields: req, err
func (_m *MockDispatcher) Finish(req *types.Request, err error) {
	_m.Called(req, err)
}

// MockDispatcher_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockDispatcher_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - req *types.Request
//   - err error
func (_e *MockDispatcher_Expecter) Finish(req interface{}, err interface{}) *MockDispatcher_Finish_Call {
	return &MockDispatcher_Finish_Call{Call: _e.mock.On("Finish", req, err)}
}

func (_c *MockDispatcher_Finish_Call) Run(run func(req *types.Request, err error)) *MockDispatcher_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.Request), args[1].(error))
	})
	return _c
}

func (_c *MockDispatcher_Finish_Call) Return() *MockDispatcher_Finish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Finish_Call) RunAndReturn(run func(*types.Request, error)) *MockDispatcher_Finish_Call {
	_c.Run(run)
	return _c
}

// LoadSavedState provides a mock function with no fields
func (_m *MockDispatcher) LoadSavedState() ([]*types.Request, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadSavedState")
	}

	var r0 []*types.Request
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*types.Request, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*types.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Request)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDispatcher_LoadSavedState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSavedState'
type MockDispatcher_LoadSavedState_Call struct {
	*mock.Call
}

// LoadSavedState is a helper method to define mock.On call
func (_e *MockDispatcher_Expecter) LoadSavedState() *MockDispatcher_LoadSavedState_Call {
	return &MockDispatcher_LoadSavedState_Call{Call: _e.mock.On("LoadSavedState")}
}

func (_c *MockDispatcher_LoadSavedState_Call) Run(run func()) *MockDispatcher_LoadSavedState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatcher_LoadSavedState_Call) Return(_a0 []*types.Request, _a1 error) *MockDispatcher_LoadSavedState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDispatcher_LoadSavedState_Call) RunAndReturn(run func() ([]*types.Request, error)) *MockDispatcher_LoadSavedState_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function with given fields: ctx
func (_m *MockDispatcher) Pull(ctx context.Context) (*types.Request, bool) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 *types.Request
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context) (*types.Request, bool)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.Request); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockDispatcher_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockDispatcher_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDispatcher_Expecter) Pull(ctx interface{}) *MockDispatcher_Pull_Call {
	return &MockDispatcher_Pull_Call{Call: _e.mock.On("Pull", ctx)}
}

func (_c *MockDispatcher_Pull_Call) Run(run func(ctx context.Context)) *MockDispatcher_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDispatcher_Pull_Call) Return(_a0 *types.Request, _a1 bool) *MockDispatcher_Pull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDispatcher_Pull_Call) RunAndReturn(run func(context.Context) (*types.Request, bool)) *MockDispatcher_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with no fields
func (_m *MockDispatcher) Shutdown() {
	_m.Called()
}

// MockDispatcher_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockDispatcher_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockDispatcher_Expecter) Shutdown() *MockDispatcher_Shutdown_Call {
	return &MockDispatcher_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockDispatcher_Shutdown_Call) Run(run func()) *MockDispatcher_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatcher_Shutdown_Call) Return() *MockDispatcher_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Shutdown_Call) RunAndReturn(run func()) *MockDispatcher_Shutdown_Call {
	_c.Run(run)
	return _c
}

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher {
	mock := &MockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
