// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/Khaym03/kumo/internal/pkg/types"
)

// MockEnqueuer is an autogenerated mock type for the Enqueuer type
type MockEnqueuer struct {
	mock.Mock
}

type MockEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnqueuer) EXPECT() *MockEnqueuer_Expecter {
	return &MockEnqueuer_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: reqs
func (_m *MockEnqueuer) Enqueue(reqs ...*types.Request) {
	_va := make([]interface{}, len(reqs))
	for _i := range reqs {
		_va[_i] = reqs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockEnqueuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockEnqueuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - reqs ...*types.Request
func (_e *MockEnqueuer_Expecter) Enqueue(reqs ...interface{}) *MockEnqueuer_Enqueue_Call {
	return &MockEnqueuer_Enqueue_Call{Call: _e.mock.On("Enqueue",
		append([]interface{}{}, reqs...)...)}
}

func (_c *MockEnqueuer_Enqueue_Call) Run(run func(reqs ...*types.Request)) *MockEnqueuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*types.Request, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(*types.Request)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockEnqueuer_Enqueue_Call) Return() *MockEnqueuer_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnqueuer_Enqueue_Call) RunAndReturn(run func(...*types.Request)) *MockEnqueuer_Enqueue_Call {
	_c.Run(run)
	return _c
}

// NewMockEnqueuer creates a new instance of MockEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnqueuer {
	mock := &MockEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
