// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/Khaym03/kumo/internal/pkg/proxy"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProxiesDownloader creates a new instance of MockProxiesDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProxiesDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProxiesDownloader {
	mock := &MockProxiesDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProxiesDownloader is an autogenerated mock type for the ProxiesDownloader type
type MockProxiesDownloader struct {
	mock.Mock
}

type MockProxiesDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProxiesDownloader) EXPECT() *MockProxiesDownloader_Expecter {
	return &MockProxiesDownloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockProxiesDownloader
func (_mock *MockProxiesDownloader) Download() ([]proxy.Proxy, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []proxy.Proxy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]proxy.Proxy, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []proxy.Proxy); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]proxy.Proxy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProxiesDownloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockProxiesDownloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
func (_e *MockProxiesDownloader_Expecter) Download() *MockProxiesDownloader_Download_Call {
	return &MockProxiesDownloader_Download_Call{Call: _e.mock.On("Download")}
}

func (_c *MockProxiesDownloader_Download_Call) Run(run func()) *MockProxiesDownloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProxiesDownloader_Download_Call) Return(proxys []proxy.Proxy, err error) *MockProxiesDownloader_Download_Call {
	_c.Call.Return(proxys, err)
	return _c
}

func (_c *MockProxiesDownloader_Download_Call) RunAndReturn(run func() ([]proxy.Proxy, error)) *MockProxiesDownloader_Download_Call {
	_c.Call.Return(run)
	return _c
}
