// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/Khaym03/kumo/internal/pkg/proxy"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRemoteBrowserURLBuilder creates a new instance of MockRemoteBrowserURLBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteBrowserURLBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteBrowserURLBuilder {
	mock := &MockRemoteBrowserURLBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemoteBrowserURLBuilder is an autogenerated mock type for the RemoteBrowserURLBuilder type
type MockRemoteBrowserURLBuilder struct {
	mock.Mock
}

type MockRemoteBrowserURLBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteBrowserURLBuilder) EXPECT() *MockRemoteBrowserURLBuilder_Expecter {
	return &MockRemoteBrowserURLBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockRemoteBrowserURLBuilder
func (_mock *MockRemoteBrowserURLBuilder) Build() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRemoteBrowserURLBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockRemoteBrowserURLBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockRemoteBrowserURLBuilder_Expecter) Build() *MockRemoteBrowserURLBuilder_Build_Call {
	return &MockRemoteBrowserURLBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockRemoteBrowserURLBuilder_Build_Call) Run(run func()) *MockRemoteBrowserURLBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRemoteBrowserURLBuilder_Build_Call) Return(s string, err error) *MockRemoteBrowserURLBuilder_Build_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRemoteBrowserURLBuilder_Build_Call) RunAndReturn(run func() (string, error)) *MockRemoteBrowserURLBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// WithProxy provides a mock function for the type MockRemoteBrowserURLBuilder
func (_mock *MockRemoteBrowserURLBuilder) WithProxy(proxy1 proxy.Proxy) {
	_mock.Called(proxy1)
	return
}

// MockRemoteBrowserURLBuilder_WithProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithProxy'
type MockRemoteBrowserURLBuilder_WithProxy_Call struct {
	*mock.Call
}

// WithProxy is a helper method to define mock.On call
//   - proxy1 proxy.Proxy
func (_e *MockRemoteBrowserURLBuilder_Expecter) WithProxy(proxy1 interface{}) *MockRemoteBrowserURLBuilder_WithProxy_Call {
	return &MockRemoteBrowserURLBuilder_WithProxy_Call{Call: _e.mock.On("WithProxy", proxy1)}
}

func (_c *MockRemoteBrowserURLBuilder_WithProxy_Call) Run(run func(proxy1 proxy.Proxy)) *MockRemoteBrowserURLBuilder_WithProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proxy.Proxy
		if args[0] != nil {
			arg0 = args[0].(proxy.Proxy)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRemoteBrowserURLBuilder_WithProxy_Call) Return() *MockRemoteBrowserURLBuilder_WithProxy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRemoteBrowserURLBuilder_WithProxy_Call) RunAndReturn(run func(proxy1 proxy.Proxy)) *MockRemoteBrowserURLBuilder_WithProxy_Call {
	_c.Run(run)
	return _c
}
