// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/Khaym03/kumo/internal/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestFilter creates a new instance of MockRequestFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestFilter {
	mock := &MockRequestFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestFilter is an autogenerated mock type for the RequestFilter type
type MockRequestFilter struct {
	mock.Mock
}

type MockRequestFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestFilter) EXPECT() *MockRequestFilter_Expecter {
	return &MockRequestFilter_Expecter{mock: &_m.Mock}
}

// Filter provides a mock function for the type MockRequestFilter
func (_mock *MockRequestFilter) Filter(req *types.Request) (bool, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*types.Request) (bool, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*types.Request) bool); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*types.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestFilter_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockRequestFilter_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - req *types.Request
func (_e *MockRequestFilter_Expecter) Filter(req interface{}) *MockRequestFilter_Filter_Call {
	return &MockRequestFilter_Filter_Call{Call: _e.mock.On("Filter", req)}
}

func (_c *MockRequestFilter_Filter_Call) Run(run func(req *types.Request)) *MockRequestFilter_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types.Request
		if args[0] != nil {
			arg0 = args[0].(*types.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestFilter_Filter_Call) Return(b bool, err error) *MockRequestFilter_Filter_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRequestFilter_Filter_Call) RunAndReturn(run func(req *types.Request) (bool, error)) *MockRequestFilter_Filter_Call {
	_c.Call.Return(run)
	return _c
}
