// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelKumo() {
  return window['go']['main']['App']['CancelKumo']();
}

export function RunKumo(arg1) {
  return window['go']['main']['App']['RunKumo'](arg1);
}
