// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelKumo() {
  return window['go']['main']['App']['CancelKumo']();
}

export function LoadWorkFlows() {
  return window['go']['main']['App']['LoadWorkFlows']();
}

export function RunKumo(arg1) {
  return window['go']['main']['App']['RunKumo'](arg1);
}

export function SaveWorkFlow(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkFlow'](arg1, arg2);
}

export function ShowError(arg1) {
  return window['go']['main']['App']['ShowError'](arg1);
}
